# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        <!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flowerie - Fleurs en plastique de luxe</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <!-- En-tête -->
    <header>
        <div class="logo">
            <h1>Flowerie</h1>
        </div>
        <nav>
            <ul>
                <li><a href="#accueil">Accueil</a></li>
                <li><a href="#produits">Produits</a></li>
                <li><a href="#contact">Contact</a></li>
                <li><a href="#panier">Panier</a></li>
            </ul>
        </nav>
    </header>

    <!-- Page d'Accueil -->
    <section id="accueil" class="hero">
        <div class="hero-content">
            <h2>Bienvenue chez Flowerie</h2>
            <p>Découvrez nos fleurs en plastique élégantes et durables pour sublimer votre intérieur.</p>
            <a href="#produits" class="btn">Explorez nos produits</a>
        </div>
    </section>

    <!-- Produits -->
    <section id="produits" class="produits">
        <h2>Nos Produits</h2>
        <div class="produit">
            <img src="rose.jpg" alt="Bouquet de Roses Poudrées">
            <h3>Bouquet de Roses Poudrées</h3>
            <p class="prix">150 MAD</p>
            <p>Un bouquet élégant de roses en plastique, idéal pour toutes vos décorations.</p>
            <a href="#panier" class="btn">Ajouter au panier</a>
        </div>
        <!-- Ajouter plus de produits ici -->
    </section>

    <!-- Panier -->
    <section id="panier" class="panier">
        <h2>Votre Panier</h2>
        <p>Aucun produit dans le panier pour le moment.</p>
    </section>

    <!-- Contact -->
    <section id="contact" class="contact">
        <h2>Contactez-nous</h2>
        <form action="#" method="post">
            <label for="nom">Nom</label>
            <input type="text" id="nom" name="nom" required>

            <label for="email">Email</label>
            <input type="email" id="email" name="email" required>

            <label for="message">Message</label>
            <textarea id="message" name="message" required></textarea>

            <button type="submit">Envoyer</button>
        </form>
    </section>

    <!-- Pied de page -->
    <footer>
        <p>&copy; 2025 Flowerie. Tous droits réservés.</p>
    </footer>
</body>
</html>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f4;
}

header {
    background-color: #fff;
    padding: 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-bottom: 1px solid #ddd;
}

header .logo h1 {
    font-size: 24px;
    color: #ff6f61; /* Rose élégant */
}

header nav ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
    display: flex;
}

header nav ul li {
    margin-left: 20px;
}

header nav ul li a {
    text-decoration: none;
    color: #333;
    font-size: 16px;
}

.hero {
    background: url('fleurs.jpg') no-repeat center center/cover;
    color: white;
    text-align: center;
    padding: 80px 20px;
}

.hero h2 {
    font-size: 48px;
}

.hero p {
    font-size: 18px;
}

.hero .btn {
    padding: 12px 20px;
    background-color: #ff6f61;
    color: white;
    text-decoration: none;
    border-radius: 5px;
    font-size: 16px;
}

.produits {
    padding: 40px 20px;
    text-align: center;
}

.produits h2 {
    font-size: 32px;
    margin-bottom: 20px;
}

.produit {
    display: inline-block;
    width: 30%;
    margin: 20px;
    background-color: #fff;
    padding: 20px;
    border: 1px solid #ddd;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.produit img {
    width: 100%;
    height: auto;
    border-radius: 8px;
}

.produit h3 {
    font-size: 24px;
    color: #333;
}

.produit .prix {
    color: #ff6f61;
    font-size: 20px;
    font-weight: bold;
}

.produit .btn {
    padding: 10px 15px;
    background-color: #ff6f61;
    color: white;
    text-decoration: none;
    border-radius: 5px;
    font-size: 16px;
    display: inline-block;
    margin-top: 10px;
}

.contact {
    padding: 40px 20px;
    background-color: #fff;
}

.contact form {
    display: grid;
    grid-gap: 15px;
}

.contact label {
    font-size: 18px;
}

.contact input, .contact textarea {
    padding: 10px;
    font-size: 16px;
    border: 1px solid #ddd;
    border-radius: 5px;
}

.contact button {
    padding: 12px 20px;
    background-color: #ff6f61;
    color: white;
    font-size: 16px;
    border: none;
    border-radius: 5px;
}

footer {
    background-color: #fff;
    text-align: center;
    padding: 20px;
    border-top: 1px solid #ddd;
}
